# Generated by Django 3.1.5 on 2021-03-24 14:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('type', models.SmallIntegerField()),
                ('nummer', models.SmallIntegerField()),
                ('room_code', models.CharField(default='', max_length=8)),
                ('used', models.BooleanField(default=False)),
                ('inUse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('message', models.TextField(max_length=300, null=True)),
                ('player_code', models.CharField(max_length=8)),
                ('room_code', models.CharField(max_length=8)),
                ('seeable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('started', models.BooleanField(default=False)),
                ('maximal_player', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spieler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('username', models.CharField(default='', max_length=100)),
                ('host', models.CharField(default='', max_length=50, unique=True)),
                ('type', models.SmallIntegerField(default=0)),
                ('room_code', models.CharField(default='', max_length=8)),
                ('dealerTries', models.SmallIntegerField(default=0, null=True)),
                ('guesserTries', models.SmallIntegerField(default=0, null=True)),
                ('canTip', models.BooleanField(default=False)),
            ],
        ),
    ]
